services:
  nextjs:
    container_name: nextjs
    build:
      context: ./spacez
      dockerfile: ./Dockerfile
    volumes:
      - node_modules:/app/frontend/node_modules
      - logs:/root/.npm/_logs
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80

volumes:
  node_modules:
  logs:
